### ISSUE TITLE
Getting "This webpage has a redirect loop"

### ISSUE THREAD

**Issue by jdariasl80** [keycloak/keycloak-nodejs-connect#1]
Hi!

I'm getting this message "This webpage has a redirect loop" after the success login. I've narrow the problem in this file "grant-manager.js". 
var verify = crypto.createVerify('RSA-SHA256');
  verify.update( token.signed );
  if ( ! verify.verify( this.publicKey, token.signature, 'base64' ) ) {
 return;
  }
the problem is that the verify function fails so, the function validateToken returns, so it try again over and over.

I'm using keycloak 1.0.1 (latest version didn't work for me) and the latest version of keycloak-nodejs

Thanks in advance.

**Comment by bobmcwhirter** [comment]
So we probably should add a throw in there in the case of non-verification, mayhap.

**Comment by carlosthe19916** [comment]
I have the same error, once the aplication has login then it generate redirects lop. how can i solve this?

**Comment by bobmcwhirter** [comment]
Do you have a sample app and workflow that causes this?

Is it due to a failed authentication attempt?  Or do you successfully login, but then the app redirects continuously?

**Comment by carlosthe19916** [comment]
here is a simple project for sample https://github.com/carlosthe19916/keycloak-nodejs-aplication.

I'm using a keycloak server on openshift and i have a user with:
username: user
password: 123456

keycloak login successfully, but then the app redirects and causes loop.

**Comment by bobmcwhirter** [comment]
Thanks, I'll try to poke into this today or tomorrow.

**Comment by carlosthe19916** [comment]
Thank you very much, I am very grateful.

**Comment by bobmcwhirter** [comment]
So, I'm poking around and here's what I've found so far...

a) Seems that node.js (at least on my machine) isn't smart enough to use the correct Agent (http vs https), and I was getting errors about "expected http not https" or whatnot when attempting to authenticate against your Keycloak.

b) Once I patched that, I now am finding that it's correctly exchanging a code for a token on your Keycloak, but the signature isn't verifying.

Could you double-check the keycloak.json and ensure that your server public-key matches the one in the sample app you linked to above?

c) I am *not* finding any loops, but I am experiencing a hang within ensureFreshness(), where apparently we're not dealing with non-valid/non-refreshable tokens.

Let me know once you verify the keycloak.json.

Else, if you're willing to send me a private message to bob @ <my last name>.org with the credentials to your Keycloak installation, that'd be useful maybe.

Thanks!

**Comment by carlosthe19916** [comment]
Good morning, here i have a keycloak 1.1.0.Final server

*auth server url:*
https://keycloak-sistcoopee.rhcloud.com/auth/admin/master/console/#/realms/demo
*admin user:* admin
*admin password:* admin

There is a *demo *realm and a application with *keycloak-nodejs*
<https://keycloak-sistcoopee.rhcloud.com/auth/admin/master/console/#/realms/demo/applications/f1467bd2-2490-4444-a649-e97f95852c36>
 name

I configure a simple *app.js* as
https://github.com/carlosthe19916/keycloak-nodejs-aplication/blob/master/app.js
and a *keycloak.json* as
https://github.com/carlosthe19916/keycloak-nodejs-aplication/blob/master/keycloak.json

When i go to *http://localhost:3000/index.html
<http://localhost:3000/index.html> *the system go to
https://keycloak-sistcoopee.rhcloud.com/auth/realms/demo/tokens/login?client_id=keycloak-nodejs&state=3d7cf6c7-2f80-47cd-a789-352e2d604ced&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Findex.html%3Fauth_callback%3D1

In the keycloak's login i enter
*username*: user
*password*: 123456

The login is correct bu there is a loop, the system can't redirect to
*http://localhost:3000/index.html
<http://localhost:3000/index.html>*

*Please help me to configure this simple sample.*

*NOTE: *i'm trying to user MEAN.IO with Keycloak but i have the loop error
and then an No 'Access-Control-Allow-Origin' header error. First i would
like to solve the loop error.




2015-04-17 14:07 GMT-05:00 Bob McWhirter <notifications@github.com>:

> So, I'm poking around and here's what I've found so far...
>
> a) Seems that node.js (at least on my machine) isn't smart enough to use
> the correct Agent (http vs https), and I was getting errors about "expected
> http not https" or whatnot when attempting to authenticate against your
> Keycloak.
>
> b) Once I patched that, I now am finding that it's correctly exchanging a
> code for a token on your Keycloak, but the signature isn't verifying.
>
> Could you double-check the keycloak.json and ensure that your server
> public-key matches the one in the sample app you linked to above?
>
> c) I am *not* finding any loops, but I am experiencing a hang within
> ensureFreshness(), where apparently we're not dealing with
> non-valid/non-refreshable tokens.
>
> Let me know once you verify the keycloak.json.
>
> Else, if you're willing to send me a private message to bob @ .org with
> the credentials to your Keycloak installation, that'd be useful maybe.
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/keycloak/keycloak-nodejs/issues/1#issuecomment-94054607>
> .
>



-- 
Carlos E. Feria Vila

**Comment by carlosthe19916** [comment]
Good morning, here i have a keycloak 1.1.0.Final server

## auth server url:*
https://keycloak-sistcoopee.rhcloud.com/auth/admin/master/console/#/realms/demo
#### admin user:* admin
#### admin password:* admin

There is a *demo *realm and a application with *keycloak-nodejs*
<https://keycloak-sistcoopee.rhcloud.com/auth/admin/master/console/#/realms/demo/applications/f1467bd2-2490-4444-a649-e97f95852c36>
 name

I configure a simple *app.js* as
https://github.com/carlosthe19916/keycloak-nodejs-aplication/blob/master/app.js
and a *keycloak.json* as
https://github.com/carlosthe19916/keycloak-nodejs-aplication/blob/master/keycloak.json

When i go to *http://localhost:3000/index.html
<http://localhost:3000/index.html> *the system go to
https://keycloak-sistcoopee.rhcloud.com/auth/realms/demo/tokens/login?client_id=keycloak-nodejs&state=3d7cf6c7-2f80-47cd-a789-352e2d604ced&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Findex.html%3Fauth_callback%3D1

In the keycloak's login i enter
*username*: user
*password*: 123456

The login is correct bu there is a loop, the system can't redirect to
*http://localhost:3000/index.html
<http://localhost:3000/index.html>*

*Please help me to configure this simple sample.*

*NOTE: *i'm trying to user MEAN.IO with Keycloak but i have the loop error
and then an No 'Access-Control-Allow-Origin' header error. First i would
like to solve the loop error.




2015-04-17 14:07 GMT-05:00 Bob McWhirter <notifications@github.com>:

> So, I'm poking around and here's what I've found so far...
>
> a) Seems that node.js (at least on my machine) isn't smart enough to use
> the correct Agent (http vs https), and I was getting errors about "expected
> http not https" or whatnot when attempting to authenticate against your
> Keycloak.
>
> b) Once I patched that, I now am finding that it's correctly exchanging a
> code for a token on your Keycloak, but the signature isn't verifying.
>
> Could you double-check the keycloak.json and ensure that your server
> public-key matches the one in the sample app you linked to above?
>
> c) I am *not* finding any loops, but I am experiencing a hang within
> ensureFreshness(), where apparently we're not dealing with
> non-valid/non-refreshable tokens.
>
> Let me know once you verify the keycloak.json.
>
> Else, if you're willing to send me a private message to bob @ .org with
> the credentials to your Keycloak installation, that'd be useful maybe.
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/keycloak/keycloak-nodejs/issues/1#issuecomment-94054607>
> .
>



-- 
Carlos E. Feria Vila

**Comment by bobmcwhirter** [comment]
Hiya--

Thanks, I've debugged this against your OpenShift-hosted keycloak, I think.

I've published 0.0.14 of connect-keycloak (and keycloak-auth-utils) which should do the following:

a) Correctly use the HTTPS agent when necessary
b) Include the original redirect_uri when performing the purely server-side code-to-token dance with the Keycloak server.  

The (b) change is because of this chunk of code in Keycloak itself

https://github.com/keycloak/keycloak/blob/1.1.0.Final/services/src/main/java/org/keycloak/protocol/oidc/OpenIDConnectService.java#L605-L613

Which seems decidedly weird to me, that the server-to-server dance should require that, but I reckon it's got something to do with ensuring non-spoofing the code-to-token requester.  I've inquired with the Keycloak team.  I'll follow-up once I learn more.

Give the 0.0.14 version of connect-keycloak a whirl and let me know.  I'll leave this open until you verify that it works, if it works.

**Comment by bobmcwhirter** [comment]
fwiw, npm registry seems to cache stuff quite a bit, but 0.0.14 is there

eduardo:~ bob$ npm view connect-keycloak

{ name: 'connect-keycloak',
  description: 'Keycloak Connect Middleware',
  'dist-tags': { latest: '0.0.14' },

**Comment by carlosthe19916** [comment]
Than you very much. I was testing the keycloak-nodejs and:

* there is a error "Protocol:https: not supported."
* i solved it replacing

var request = http.request( options, function(response) {
    var json = '';
    response.on('data', function(d) {
      json += d.toString();
    });
    response.on( 'end', function() {
      try {
        var grant = self.createGrant( json );
        return deferred.resolve( grant );
      } catch (err) {
        return deferred.reject( err );
      }
    });
  } );

for

var protocol;
  if ( options.protocol == 'https:' ) {
      protocol = https;
  } else {
      protocol = http;
  }
  
  var request = protocol.request( options, function(response) {
    var json = '';
    response.on('data', function(d) {
      json += d.toString();
    });
    response.on( 'end', function() {
      try {
        var grant = self.createGrant( json );
        return deferred.resolve( grant );
      } catch (err) {
        return deferred.reject( err );
      }
    });
  } );

**Comment by bobmcwhirter** [comment]
I apologize, apparently I was editing the entirely wrong repositories before I moved them all to the Keycloak organization.  I'll spend some time this afternoon getting everything straightened out.

In the wrong repositories, I've adjusted the http-vs-https stuff but, alas, in the wrong place.

Sigh.

**Comment by carlosthe19916** [comment]
I am very grateful for your help. My last message is related to https://github.com/bobmcwhirter/keycloak-auth-utils repository, i was testing your personal repository and i see the error described in my last message.

**Comment by bobmcwhirter** [comment]
Yah, I like your solution, instead of how I'm juggling Agents around.  I'll apply that change, to the correct repository, and try to publish 0.0.15 later today.

Thanks for your help!

**Comment by bobmcwhirter** [comment]
Okay, I've applied your protocol solution, in addition to getting all other changes jammed into the correct repository, along with a git tag.

https://github.com/keycloak/keycloak-nodejs/tree/0.0.15

NPMs have been published.

Let me know if 0.0.15 works better now.
