### ISSUE TITLE
Integration with Restify

### ISSUE THREAD

**Issue by jaekunchoi** [keycloak/keycloak-nodejs-connect#2]
I've been looking at below to integrate with Node.js Restify application.

http://keycloak.github.io/keycloak-nodejs/connect/index.html

When do you plan to release the stable version of nodejs adaptor?

I also tried to integrate with Restify but it seems to hang without any callback with infinite loop on the browser. This happens when I put in protect() method for .get request. I suppose it's due to requirement of connect middleware. Basically the code that I have is:

server.get({url: '/hb'}, kc.protect(), function(req, res) {
 res.send("ok");
});

Any of your help would be greatly appreciated.

**Comment by bobmcwhirter** [comment]
Hey, glad to have some feedback.  Sorry it’s not working for ya.

I’d hoped this one was stable:

	https://www.npmjs.com/package/connect-keycloak

I tested against Express, but figured Connect should work also.  I’ll take a look at that shortly.

Do you have a quick reproductive test-case I could clone out of git and give a whirl?  Or just a gist?

Thanks!

-Bob

**Comment by bobmcwhirter** [comment]
I just published 0.0.14 which might help this problem.

**Comment by hybmg57** [comment]
Great! Where can I get this?

**Comment by bobmcwhirter** [comment]
From the NPM registry

https://www.npmjs.com/package/connect-keycloak

Just specify version 0.0.14 in your package.json

**Comment by UberJohn** [comment]
Is this still an open issue?

Using v 0.0.16 and it seems to be hanging still.
