### ISSUE TITLE
Cannot load example protected resource

### ISSUE THREAD

**Issue by Handfish** [keycloak/keycloak-nodejs-connect#310]
### Describe the bug

After starting the docker image and adding the realm via the import button and uploading `nodejs-example-realm.json`, I can login but I cannot access the protected route and receive "Access Denied".

### Version

Keycloak 15.1.0

### Expected behavior

Result and Access Granted Event

### Actual behavior

Access denied

### How to Reproduce?

`docker run -p 8080:8080 -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin jboss/keycloak`

Add the realm via the import button and uploading `nodejs-example-realm.json`

```
npm link ../
npm install
npm start
```

Open the browser at http://localhost:3000/ and login with username: 'user', and password: 'password'.

click protected route

**Comment by Handfish** [comment]
Added User to Authorization Scopes and a View / Write policy in the nodejs-apiserver client. Can now access protected resource.

**Comment by DurandA** [comment]
> Added User to Authorization Scopes and a View / Write policy in the nodejs-apiserver client. Can now access protected resource.

@Handfish Could you please elaborate on the steps you performed? I am evaluating Keycloak and have zero experience with it.

Thank you.

**Comment by ujwalparker** [comment]
@DurandA the realm creation needs a few addition for the permission to work. @Handfish 

[The gist has the updates.](https://gist.github.com/ujwalparker/7e1c8cda7839461a1b9ce87ab3281e29)

Added client roles
`"client": {
  "nodejs-apiserver": [
    {
      "name": "user",
      "clientRole": true
    },
    {
      "name": "admin",
      "clientRole": true
    }
  ],
  "nodejs-connect": []
}`


Added policy to authorization
` "policies": [
{
  "name": "Default Policy",
  "description": "A policy that grants access only for users within this realm",
  "type": "role",
  "config": {
    "roles": "[{\"id\":\"user\",\"required\":false},{\"id\":\"nodejs-apiserver/admin\",\"required\":false},{\"id\":\"nodejs-apiserver/user\",\"required\":false},{\"id\":\"admin\",\"required\":false}]"
  }
},
{
  "name": "Default Permission",
  "description": "A permission that applies to the default resource type",
  "type": "resource",
  "config": {
    "resources": "[\"resource\"]",
    "applyPolicies": "[\"Default Policy\"]"
  }
}
]`


Added scope to authorization
`"scopes": [
  {
    "name": "write"
  },
  {
    "name": "view"
  }
  ]`
