### ISSUE TITLE
Send coverage results to coveralls via github actions

### ISSUE THREAD

**Issue by helio-frota** [keycloak/keycloak-nodejs-connect#326]
### Description

It seems that the last update to coveralls was done ~3 years ago via travis CI.
This repository [new-module-starter](https://github.com/nodeshift/new-module-starter) has a CI config that can help with that.
( This repository is a kind of implementation of some development recommendations from [Node.js Reference Architecture](https://github.com/nodeshift/nodejs-reference-architecture/tree/main/docs/development) ).

**Comment by helio-frota** [comment]
hi all, I'm closing this :+1:

**Comment by jonkoops** [comment]
Thanks for reporting this. I've created a PR to remove the badges since they are not really essential (#432).
