### ISSUE TITLE
Client side request

### ISSUE THREAD

**Issue by carlosthe19916** [keycloak/keycloak-nodejs-connect#4]
Good night, i'm using keycloak-nodejs adapter. I can access to keycloak using expressjs, but i need to send request from client side too.

The keycloak-nodejs can intercept all client side request to access to a .war restfull service?

Here is a image which represents the question.  https://docs.google.com/drawings/d/1zPRtS_-pPKI3fuAgkRvTzXfBODYFzEh7DCfnOf8krmc/edit?usp=sharing

**Comment by bobmcwhirter** [comment]
Do you want the node.js app to proxy calls to the .war, or have the client directly speak to the .war?

If you want the client to speak directly to the .war, have you exposed the JSON Web Token from the node.js app to the javascript client, and using it as a Bearer token?

From your diagram, I think the error you're receiving is on the client side?  The access-control-allowed-origin is a CORS header that should be present in the preflight response from the .war.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

Before making a request, the browser/client typically makes a pre-flight OPTIONS request with a few headers and expects a few specific headers in return to know if it should further make the actual request. 

So, you GET is actually an OPTIONS followed by a GET, if the OPTIONS matches everything correctly and is allowed by the CORS.

If you turn on the Chrome network debugger, you should be able to see the OPTIONS request flow (assuming Javascript client is talking to the .war) and dig into what headers are present or missing on the initial pre-flight OPTIONS request.

If you want the node.js to proxy requests between the client and the .war, you can still do the preflight, or simply construct the GET to be sufficiently happy for the server (including Origin: headers and such).

**Comment by carlosthe19916** [comment]
I will speak directly to the .war, so how can i obtain the token string from Keycloak object?

````javascript
// basic initialization of keycloak
var keycloak = new Keycloak();
````

keycloak object has the methods:
* middleware (options)
* protect (spec)
* authenticated (request)
* deauthenticated (request)
* accessDenied (request, response)

/*ignore methods*/
* getGrant (request, response)
* storeGrant (grant, request, response)
* unstoreGrant (sessionId)
* getGrantFromCode (code, request, response)
* loginUrl (uuid, redirectUrl )
* logoutUrl (redirectUrl)
* accountUrl ()
* getAccount (token)

### where i find a method like ### keycloak.getToken()

**Comment by bobmcwhirter** [comment]
I think we probably need to document getGrant(req,resp) or provide a clear path.

You can use keycloak.getGrant() which returns a promise that should resolve to the grant.js implementation of the grant from keycloak.

toString() on that object should provide the original valid keycloak JSON WebToken thing.

https://github.com/keycloak/keycloak-nodejs/blob/master/auth-utils/grant.js#L63-L65

Additionally, the grant-attacher middleware attaches it as request.auth.grant, so you can shuttle it to your client-side application from one of your endpoints:

https://github.com/keycloak/keycloak-nodejs/blob/master/auth-utils/grant.js#L63-L65

It might be useful for us to provide an optional middleware endpoint that'd respond to a given URL to provide the token as application/json, RESTfully, similar to how we provide the login/logout and admin endpoints.

Give it a whirl with the existing code and let me know how you think it could work better.

Thanks!

**Comment by bobmcwhirter** [comment]
btw, if you do IRC, I tend to idle in #keycloak on irc.freenode.net.
