### ISSUE TITLE
Support for HTTP Basic Authentication

### ISSUE THREAD

**Issue by khanisak** [keycloak/keycloak-nodejs-connect#417]
### Description

Based on keycloak documentation on java adapter, [here](https://www.keycloak.org/docs/latest/securing_apps/#_jboss_adapter)

There is an option to activate HTTP basic authentication feature. 

```json
"enable-basic-auth" : false
```

Description of the configuration,
```
OPTIONAL. This tells the adapter to also support basic authentication. If this option is enabled, then secret must also be provided. The default value is false.
```

The "Basic" HTTP authentication allow us to transmits credentials as user ID/password pairs, encoded using base64 in the authorization request headers, like this.

```
Authorization: basic dXNlcm5hbWVrdTpwYXNzd29yZGt1
```
It seems keycloak nodejs adapter does not have this option yet, would be great to see this feature added in the future.

**Comment by jonkoops** [comment]
The Node.js adapter has been deprecated, so we will not be adding any new features any longer. More information can be found in the [announcement blog post](https://www.keycloak.org/2022/02/adapter-deprecation).
