### ISSUE TITLE
Docs on deprication of nodejs adapter

### ISSUE THREAD

**Issue by cisar2218** [keycloak/keycloak-nodejs-connect#512]
### Description

For users it would be handy to add warning with alternatives to docs [here](https://www.keycloak.org/docs/22.0.5/securing_apps/#_nodejs_adapter). Perhaps link to ["nodejs adapter deprication update" post](https://www.keycloak.org/2023/03/adapter-deprecation-update.html) would do the job.
 
**At npm:**
> Warning This package is deprecated and will be removed in the future. We will shortly provide more details on removal date, and recommended alternatives.

To improve the statement I suggest provide more details at least link to [this](https://github.com/keycloak/keycloak/discussions/9818) thread (for me it took quite some time to find this discussion with handy tips/alternatives from community).

### Details
For more details on topic of deprication read [this](https://github.com/keycloak/keycloak/discussions/9818) related discussion.

**Comment by ttante** [comment]
Bumping this because most connectors have broken examples and getting a working node.js + keycloak solution is turning into a huge headache, with all signs pointing to needing a rewrite soon. What's worse it's not even clear why things are deprecated.

**Comment by Zysberg** [comment]
Bumping again.

**Comment by jonkoops** [comment]
We have a tracker issue on the main repository https://github.com/keycloak/keycloak/issues/31326. See also https://github.com/keycloak/keycloak-nodejs-connect/issues/492#issuecomment-2500301626
